[project]
name = "tutorial2"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "cairocffi>=1.7.1",
    "igraph>=0.11.9",
    "jupyter>=1.1.1",
    "nbconvert>=7.16.6",
    "pandas>=2.3.1",
    "plantuml>=0.3.0",
]
